require 'rbconfig'

VERSION_FILENAME_IN=File.join File.dirname(__FILE__), '../../CORNERSTONE_VERSION'
VERSION_FILENAME_OUT=File.join File.dirname(__FILE__), 'VersionGenerated.hpp'

VERSION_STR=File.read(VERSION_FILENAME_IN).strip
VERSION_MAJOR=VERSION_STR.split('.')[0].to_i
VERSION_MINOR=VERSION_STR.split('.')[1].to_i
VERSION_PATCH=VERSION_STR.split('.')[2].to_i
VERSION_STR_SAFE=VERSION_STR.gsub(/[^a-zA-Z0-9_]/, '_')

VERSION_CORNERSTONE="%d%02d%02d" % [VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH]

VERSION_RELEASE_YEAR=Time.now.strftime '%Y'
VERSION_RELEASE_MONTH_STR=Time.now.strftime '%m'
VERSION_RELEASE_MONTH=VERSION_RELEASE_MONTH_STR.sub('0', '')

CORNERSTONE_BUILD_NUMBER=ENV['CI_PIPELINE_ID'] || 0

is_windows = RbConfig::CONFIG['host_os'] =~ /mingw/i
if is_windows
  CORNERSTONE_GIT_HASH=`git log -n1 --format=%h 2>nul`
else
  CORNERSTONE_GIT_HASH=`git log -n1 --format=%h 2>/dev/null`
end

FILE_CONTENTS =<<zzz
/* Copyright (C) 2007-2013 Multi Touch Oy, Finland, http://www.multitaction.com
 *
 * This file is part of MultiTouch Cornerstone.
 *
 * All rights reserved. You may use this file only for purposes for which you
 * have a specific, written permission from Multi Touch Oy.
 *
 */

#ifndef RADIANT_VERSION_GENERATED_HPP
#define RADIANT_VERSION_GENERATED_HPP

// This file is automatically generated from CORNERSTONE_SDK_ROOT/CORNERSTONE_VERSION,
// do not modify this file manually.

#define CORNERSTONE_VERSION            #{VERSION_CORNERSTONE}
#define CORNERSTONE_VERSION_MAJOR      #{VERSION_MAJOR}
#define CORNERSTONE_VERSION_MINOR      #{VERSION_MINOR}
#define CORNERSTONE_VERSION_PATCH      #{VERSION_PATCH}
#define CORNERSTONE_FULL_VERSION_STR   "#{VERSION_STR}"
#define CORNERSTONE_SHORT_VERSION_STR  "#{VERSION_MAJOR}.#{VERSION_MINOR}"

#define CORNERSTONE_RELEASE_YEAR       #{VERSION_RELEASE_YEAR}
#define CORNERSTONE_RELEASE_MONTH      #{VERSION_RELEASE_MONTH}
#define CORNERSTONE_RELEASE_YEAR_STR   "#{VERSION_RELEASE_YEAR}"
#define CORNERSTONE_RELEASE_MONTH_STR  "#{VERSION_RELEASE_MONTH_STR}"

#define CORNERSTONE_GIT_HASH           "#{CORNERSTONE_GIT_HASH.strip}"
#define CORNERSTONE_BUILD_NUMBER       #{CORNERSTONE_BUILD_NUMBER}
#endif
zzz

if !File.exists?(VERSION_FILENAME_OUT) ||
    File.mtime(VERSION_FILENAME_OUT) < File.mtime(VERSION_FILENAME_IN) ||
    File.open(VERSION_FILENAME_OUT, 'rb').read != FILE_CONTENTS
  File.open(VERSION_FILENAME_OUT, 'wb') {|f| f.write FILE_CONTENTS }
end
